# DAY 2 AM
## MATRIX

In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [3]:
matrix = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [4]:
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
matrix.shape

(3, 2)

# Akses Elemen Matrix

In [6]:
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]
])

In [7]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#mau akses angka 6 aja
A[1][2]

6

In [9]:
A[1]

array([4, 5, 6])

In [10]:
A[1,2]

6

In [11]:
A[:,-1]

array([3, 6, 9])

In [12]:
A[:, 2]

array([3, 6, 9])

In [13]:
np.triu(A)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [14]:
np.tril(A)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [15]:
np.diag(A)

array([1, 5, 9])

In [16]:
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# **Operasi Aritmatika**
- Penjumlahan
- Pengurangan
- Pembagian
- Perkalian

## Penjumlahan
dilakukan sesuai element wise, dilakukan sesuai posisinya

In [18]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
B = np.array([[1,8,2],
             [2,1,1],
             [4,0,1]])

In [20]:
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

In [21]:
#matrix dan matrix
A + B

array([[ 2, 10,  5],
       [ 6,  6,  7],
       [11,  8, 10]])

## Pengurangan

In [22]:
A-B

array([[ 0, -6,  1],
       [ 2,  4,  5],
       [ 3,  8,  8]])

## Pembagian

In [23]:
B/A

array([[1.        , 4.        , 0.66666667],
       [0.5       , 0.2       , 0.16666667],
       [0.57142857, 0.        , 0.11111111]])

## Perkalian
- matrix-scalar
- hadamart product (element wise)
- matrix-matrix (@)

In [24]:
#matrix-scalar
10*A

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [25]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

In [27]:
#hadamart product
A * B

array([[ 1, 16,  6],
       [ 8,  5,  6],
       [28,  0,  9]])

In [28]:
np.dot(A,B)

array([[17, 10,  7],
       [38, 37, 19],
       [59, 64, 31]])

In [29]:
A.dot(B)

array([[17, 10,  7],
       [38, 37, 19],
       [59, 64, 31]])

In [30]:
#matrix-matrix yg sesungguhnya
A @ B

array([[17, 10,  7],
       [38, 37, 19],
       [59, 64, 31]])

In [31]:
C = np.array([[1,2],[3,4],[5,6]])
C

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
A @ C

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [33]:
C.shape

(3, 2)

## Transpose

In [34]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [35]:
A.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Invers
hanya berlaku untuk matriks persegi

In [36]:
D = np.array([[1,2],[3,4]])
D2 = np.array([[4,-2],[-3,1]])

In [37]:
inv_D = 1/np.linalg.det(D) * D2

In [38]:
inv_D

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [39]:
np.linalg.det(B)

8.999999999999998

In [40]:
np.linalg.inv(A)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [41]:
np.linalg.inv(D)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [42]:
np.linalg.det(A)

-9.51619735392994e-16

In [43]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
np.linalg.det(A)

-9.51619735392994e-16

In [45]:
E = np.array([[1,2,3],
[2,4,6],
[1,0,1]])

In [46]:
np.linalg.det(E)

0.0

In [47]:
np.linalg.inv(E) #karena singular matrix

LinAlgError: Singular matrix

In [ ]:
0.1 + 0.3

0.4

## Tensor
multidimensional array = Tensor
1D -> vector,
2D -> matrix

In [ ]:
#3D tensor
X = np.array([[1,4,5,6],
[4,3,7,3]])
X

array([[1, 4, 5, 6],
       [4, 3, 7, 3]])

In [ ]:
Y = np.array([[2,8,8,1],
[3,0,9,1]])
Y

array([[2, 8, 8, 1],
       [3, 0, 9, 1]])

In [ ]:
Z = np.array([[2,4,1,1],
[0,9,4,2]])
Z

array([[2, 4, 1, 1],
       [0, 9, 4, 2]])

In [ ]:
tensor = np.array([X,Y,Z])
tensor

array([[[1, 4, 5, 6],
        [4, 3, 7, 3]],

       [[2, 8, 8, 1],
        [3, 0, 9, 1]],

       [[2, 4, 1, 1],
        [0, 9, 4, 2]]])

In [ ]:
tensor.shape
#(3,2,4)= (x,y,z) -> 3 dimensi

(3, 2, 4)

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# EIGENVECTOR