# Day 2 PM
## EIGENDECOMPOSITION


In [24]:
import numpy as np

In [25]:
from numpy.linalg import eig

In [26]:
A = np.array([[1,2],[2,4]])

In [27]:
eigval,eigvec = eig(A)

In [28]:
eigval

IndexError: index 2 is out of bounds for axis 0 with size 2

In [18]:
eigvec
#vector yg ditampilkan adalah vector unit,yaitu vector yg nilainya satu


array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

## Rekonstruksi matriks

In [9]:
from numpy import diag

In [10]:
diag(eigval)

array([[0., 0.],
       [0., 5.]])

In [12]:
M = eigvec @ diag(eigval) @ inv(eigvec)
M

array([[1., 2.],
       [2., 4.]])

In [13]:
dir()

['A',
 'In',
 'M',
 'Out',
 '_',
 '_10',
 '_12',
 '_5',
 '_7',
 '_8',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__vsc_ipynb_file__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i2',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'det',
 'diag',
 'eig',
 'eigval',
 'eigvec',
 'exit',
 'get_ipython',
 'inv',
 'np',
 'os',
 'quit',
 'site',
 'sys']

## EIGENDECOMPOSITION
memecah nasi goreng jadi bumbu2. Apakah dari bumbu2 itu kita bisa merekonstruksi si nasgor tadi