# Non-Graded Challenge 5
## Fathiyah Kalamal Haq - Batch 009

LINEAR ALGEBRA 3

# Soal 1

In [19]:
from numpy.linalg import eig

In [20]:
V = np.array([[1,-1],[6,4]])
V

array([[ 1, -1],
       [ 6,  4]])

In [21]:
eigval, eigvec = eig(V)

In [22]:
eigval

array([2.5+1.93649167j, 2.5-1.93649167j])

In [23]:
eigvec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

In [24]:
u = np.array([1,3])
u

array([1, 3])

In [31]:
u_satuan = u / np.sqrt(10)
u_satuan

array([0.31622777, 0.9486833 ])

In [30]:
eigvec * np.linalg.norm(eigvec)

array([[-0.32732684+0.42257713j, -0.32732684-0.42257713j],
       [ 1.30930734+0.j        ,  1.30930734+0.j        ]])

vector u bukan vektor eigen dari matriks V karena vektor satuan u tidak sama dengan vektor eigen V. begitu pula jika matriks satuan dari vektor eigen V dikalikan dengan normnya menghasilkan nilai yg berbeda dengan vektor u. Kesimpulannya [1 3] bukanlah vektor eigen dari matriks V