# Non-Graded Challenge 4
## Fathiyah Kalamal Haq - Batch 009

LINEAR ALGEBRA 2

## Soal 1
Membuat Tensor

In [1]:
import numpy as np

In [6]:
a = np.array([[23,50],[7,12]])
b = np.array([[57,67],[99,43]])
c = np.array([[75,21],[57,12]])
d = np.array([[87,26],[18,84]])
print(a.shape, b.shape, c.shape, d.shape)

(2, 2) (2, 2) (2, 2) (2, 2)


In [10]:
list_matrix = [a,b,c,d]
T = np.array(list_matrix)
T

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

## Soal 2

In [15]:
A = np.array([[23,50,19],
            [7,12,109],
            [57,67,98]
            ])
print(A)
print(A.shape)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
(3, 3)


In [16]:
B = np.array([17,22,19])
print(B)
print(B.shape)

[17 22 19]
(3,)


In [17]:
A @ B

array([1852, 2454, 4305])

## Soal 3

In [18]:
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [20]:
np.linalg.det(A)

131344.0000000002

In [21]:
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])