In [4]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
x = np.array([2, 3, 4])
poly = PolynomialFeatures(3, include_bias=False)
poly.fit_transform(x[:,None])

array([[ 2.,  4.,  8.],
       [ 3.,  9., 27.],
       [ 4., 16., 64.]])

In [5]:
poli = PolynomialFeatures(7)
poli.fit(x[:,np.newaxis])

PolynomialFeatures(degree=7)

In [7]:
x[:,np.newaxis]

array([[2],
       [3],
       [4]])

In [6]:
poli.transform(x[:,np.newaxis])

array([[1.0000e+00, 2.0000e+00, 4.0000e+00, 8.0000e+00, 1.6000e+01,
        3.2000e+01, 6.4000e+01, 1.2800e+02],
       [1.0000e+00, 3.0000e+00, 9.0000e+00, 2.7000e+01, 8.1000e+01,
        2.4300e+02, 7.2900e+02, 2.1870e+03],
       [1.0000e+00, 4.0000e+00, 1.6000e+01, 6.4000e+01, 2.5600e+02,
        1.0240e+03, 4.0960e+03, 1.6384e+04]])

In [ ]:
# p=PolynomialFeatures(3)
# p.fit_transform(x[:,np.newaxis])
# poli.transform(x[:,np.newaxis])


In [9]:
from sklearn.metrics import mean_absolute_error
for deg in [2,3,4,5,6,7]:
    poly = PolynomialFeatures(deg).fit(x[:,np.newaxis])
    x_trans = poly.transform(x[:,np.newaxis])
    model.fit(x_trans,y)
    
    y_pred = model.predict(x_trans)

    print('Poly deg = ',deg,':',mean_absolute_error(y,y_pred))


NameError: name 'model' is not defined