In [1]:
import person
print(person.devices)

['laptop', 'smartphone', 'tablet']


In [2]:
import person
print(person.name)
print(person.devices)

zacky
['laptop', 'smartphone', 'tablet']


In [3]:
from person import name, devices
print(name)
print(devices)

zacky
['laptop', 'smartphone', 'tablet']


In [4]:
!pip install pandas

## Numpy

In [5]:
!pip install numpy

In [6]:
import numpy as np

In [7]:
a = np.array([1,2,4])
a

array([1, 2, 4])

In [9]:
tinggi = [1.7,1.8,2.0]
berat = [65.5,67.2,59.2]
#berat/tinggi #gaakan bisa

In [10]:
tinggi = [1.7,1.8,2.0]
berat = [65.5,67.2,59.2]
np_tinggi = np.array(tinggi)
np_berat = np.array(berat)
np_berat/np_tinggi

array([38.52941176, 37.33333333, 29.6       ])

In [11]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.empty(4) #nilaimya selalu berubahubah

array([1., 1., 1., 1.])

In [14]:
np.arange(4)

array([0, 1, 2, 3])

In [15]:
print(np.arange(4,10,2)) #mulai dari 4 sampe 9 bedanya 2

[4 6 8]


In [21]:
arr= np.array([1,2,3,4])
arr=np.append(arr, [1,2,3])

In [22]:
np.delete(arr, 2)

array([1, 2, 4, 1, 2, 3])

In [23]:
arr

array([1, 2, 3, 4, 1, 2, 3])

In [24]:
np.sort(arr)

array([1, 1, 2, 2, 3, 3, 4])

In [25]:
a= np.array(4)
print(a) #1 dimensi

4


In [35]:
b = np.array([4,2,3])
print(b) #vektor

[4 2 3]


In [36]:
b.ndim

1

In [28]:
#2D
b = np.array([[4,2,3],[5,6,7]])
print(b)

[[4 2 3]
 [5 6 7]]


In [33]:
b.ndim

2

In [31]:
#lebih dari 2D
c = np.array([[4,2,3],[2,3,4],[1,2,3]])
print(c)

[[4 2 3]
 [2 3 4]
 [1 2 3]]


In [32]:
#mengetahui jumlah dimensi
c.ndim

2

In [37]:
c.shape #mengetahui bentuk dari 2 dimensinya itu seperti apa

(3, 3)

In [38]:
c.size #jumlah elemen 3x3

9

In [41]:
ar = np.arange(6)
print(ar)

[0 1 2 3 4 5]


In [44]:
matrix= ar.reshape(2,3)
print(matrix)

[[0 1 2]
 [3 4 5]]


In [46]:
d = np.array([1,2,3,4,5,6])
d.shape

(6,)

In [47]:
d2 = d[np.newaxis]
print(d2.shape)
print(d2)

(1, 6)
[[1 2 3 4 5 6]]


In [48]:
g = np.expand_dims(d2,axis=1)
g.shape

(1, 1, 6)

In [49]:
print(g)

[[[1 2 3 4 5 6]]]


In [50]:
arr1= np.array([2,3,7,8,9])
print(arr1[2:5])

[7 8 9]


In [51]:
print(arr1[2:5:3])#:3 nya tuh beda

[7]


In [54]:
print(arr1[:3:2])

[2 7]


In [63]:
arr2= np.array([[2,3,7,8,9],[1,3,6,8,9]])
print(arr2[0, 1:4])


[3 7 8]


In [67]:
print(arr2[0:2, 2]) #jadi arr2[row,col]

[7 6]


In [68]:
s= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(s[s>=5])

[ 5  6  7  8  9 10 11 12]


In [ ]:
#np.vstack((a1,a2))
#np.hstack((a1.a2))

In [73]:
dt= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_dt=dt.reshape(2,3,-1) 
#-1 itu kalo kita gatau perkalian berapa yg bisa merubag dari 1d ke 3d
print(new_dt)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [74]:
new_dt.shape

(2, 3, 2)

In [77]:
def convert(fahr):
    cels = fahr*1.8 +32.0
    return cels
print(convert(32))

89.6


In [87]:
def convert(fahr,kelv):
    cels = fahr*1.8 +32.0
    cels2 = kelv-273.15
    return cels
print("temperature in C =", convert(32,20))

temperature in C = 89.6


In [88]:
def tcon(ftemp):
    ctemp = (ftemp-32)*(5/9)
    ktemp = ctemp + 273.15
    return [ftemp, ktemp,ctemp]
print(tcon(72))

[72, 295.3722222222222, 22.22222222222222]


In [89]:
def fahr_to_c(temp):
    return(temp-32)*(5/9)
print(fahr_to_c(72))

22.22222222222222


In [90]:
def sum(numbers):
    total = 0
    for x in numbers:
        total += x
    return total
print(sum((8,2,3,0,7)))

20


In [91]:
def inch_to_cm(inches):
    cent = inches*2.54
    return cent
print(inch_to_cm(80))

203.2


In [96]:
def fun():
    st='jojon'
    y=35
    return st,y
#a = fun()
#print(a[0])

#a,b = fun()
#print(a)

#(fun()[0])

'jojon'

In [3]:
import pkg.mod1 as a

In [4]:
a.kitchen_sets

['fork', 'spoon', 'plate']

In [5]:
import pkg.mod2 as b

In [6]:
b.artis_kits

['gitar', 'piano', 'bass']

In [7]:
from pkg import mod1,mod2
print(mod1.kitchen_name)
mod2.artis_name

My Kitchen


'Queen'